Dev
codestates-seb/seb45_pre_035 pull request #42
Opened 2023-08-14 08:30 UTC by seolmiseon

2023-08-15 16:06 UTC, Moses-Yu requested changes

2023-08-15 16:06 UTC, Moses-Yu commented on client/src/Components/Header.js
> +        <SignIn />
버튼들을 구현해 주세요. 이 네개는 페이지 입니다.

2023-08-15 16:06 UTC, Moses-Yu commented on client/src/Pages/Home.js
> +    </LogoContainer>
Header.js 에 넣어주세요. Home.js 는 빈 컴포넌트 상태여야 합니다.

2023-08-15 16:06 UTC, Moses-Yu commented on client/src/Pages/MyPage.js
> +    </MyPageCotainer>
Header.js 에 넣어주세요. MyPage.js 는 빈 컴포넌트 상태여야 합니다.

2023-08-15 16:06 UTC, Moses-Yu commented on client/src/Pages/NewQuestion.js
> +    </MyQuestionContainer>
Header.js 에 넣어주세요. NewQuestion.js 는 빈 컴포넌트 상태여야 합니다.

2023-08-15 16:06 UTC, Moses-Yu commented on client/src/App.js
> +          <Route path="/questiondetail/:id" element={<QuestionDetail />} />
지웅님이 만들어주신 라우터들 path에 적혀있는 주소 대로 useNavigate 구현 해주세요!

2023-08-16 00:09 UTC, seolmiseon commented on client/src/Components/Header.js
> +        <SignIn />
오잉~ 리뷰가 제 로컬 터미널에 보여요... 깃허브에 안들어가도 되네요?? 신기합니다!! ㅋ 넵..

2023-08-16 00:11 UTC, Moses-Yu commented on client/src/Components/Header.js
> +        <SignIn />
오 그런가요? 첨 알았네요! ㅋㅋ

2023-08-16 04:21 UTC, Moses-Yu reviewed
클릭 상호작용 하는 부분들 hover 했을 때 커서 포인터로 변경하면 좋을 것 같습니다!!

2023-08-16 04:21 UTC, Moses-Yu commented on client/src/Components/Header.js
> +  };
주소가 잘못 되었네용

2023-08-16 04:21 UTC, Moses-Yu commented on client/src/Components/Header.js
> +        <Button src="{../../public/images/SignIn.png}" onClick={signin}>
src 부분은 삭제해도 될 것 같습니다.

2023-08-16 04:21 UTC, Moses-Yu approved these changes

2023-08-16 04:27 UTC, seolmiseon commented on client/src/Components/Header.js
> +  };
헉!!! 감사합니다

2023-08-16 05:41 UTC, Moses-Yu reviewed
감사합니다 미선님!! @seolmiseon

2023-08-16 05:42 UTC, merged